export const ADD_WISH = "ADD_WISH";
export const REMOVE_WISH = "REMOVE_WISH";
export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const EDIT_CART_QTY = "EDIT_CART_QTY";
export const CHANGE_DELIVERY = "CHANGE_DELIVERY";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_NAV_PRODUCTS = "LOAD_NAV_PRODUCTS";
export const LOAD_ONE_PRODUCT = "LOAD_ONE_PRODUCT";
export const LOAD_CATEGORY_PRODUCTS = "LOAD_CATEGORY_PRODUCTS";
export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
